import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import {
  BellRing,
  AlertTriangle,
  Flame,
  CheckCircle2,
  Clock,
  ShieldAlert,
  ArrowRight,
  Filter,
  Check
} from 'lucide-react'
import RiskBadge from '../../components/ui/RiskBadge'

export const AlertsView = () => {
  const [filterLevel, setFilterLevel] = useState('ALL')
  const [alerts, setAlerts] = useState([
    {
      id: 'ALT-1092',
      caseId: 'NHAA-2841',
      title: 'Critical Threat & Panic Spike Detected',
      description:
        'Acoustic trembling (>42dB) combined with active threat keywords indicates severe physical intimidation risk.',
      level: 'CRITICAL',
      timestamp: '12 mins ago',
      acknowledged: false,
      acknowledgedAt: null
    },
    {
      id: 'ALT-1088',
      caseId: 'NHAA-2819',
      title: 'Vulnerability Escalation Pattern (+15 pts in 48h)',
      description:
        'Longitudinal model flagged persistent stalking velocity exceeding safe monitoring thresholds.',
      level: 'HIGH',
      timestamp: '45 mins ago',
      acknowledged: true,
      acknowledgedAt: 'Today, 10:45 AM'
    },
    {
      id: 'ALT-1084',
      caseId: 'NHAA-2501',
      title: 'Follow-up Call Overdue (>45 mins)',
      description:
        'Scheduled 24-hour wellness check-in for high-stress complainant has not been logged.',
      level: 'HIGH',
      timestamp: '1 hour ago',
      acknowledged: false,
      acknowledgedAt: null
    },
    {
      id: 'ALT-1076',
      caseId: 'NHAA-2765',
      title: 'High Emotional Distress Linguistic Surge',
      description:
        'Grievance text analysis detected secondary escalation markers relating to economic coercion.',
      level: 'MODERATE',
      timestamp: '3 hours ago',
      acknowledged: true,
      acknowledgedAt: 'Today, 08:30 AM'
    }
  ])

  const handleAcknowledge = (alertId) => {
    setAlerts((prev) =>
      prev.map((a) =>
        a.id === alertId
          ? { ...a, acknowledged: true, acknowledgedAt: 'Just now' }
          : a
      )
    )
  }

  const filteredAlerts = alerts.filter((a) => {
    if (filterLevel === 'ALL') return true
    return a.level === filterLevel
  })

  return (
    <div className="space-y-6 animate-fade-in text-slate-100">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl lg:text-3xl font-black text-white tracking-tight flex items-center gap-2.5">
            <BellRing className="w-7 h-7 text-rose-400" />
            Live Triage Alerts Feed
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Real-time critical escalation warnings generated by the multimodal acoustic and NLP triage models.
          </p>
        </div>

        {/* Filter Controls */}
        <div className="flex items-center gap-2 bg-slate-900/60 backdrop-blur-xl border border-white/10 p-1 rounded-xl">
          {['ALL', 'CRITICAL', 'HIGH', 'MODERATE'].map((lvl) => (
            <button
              key={lvl}
              onClick={() => setFilterLevel(lvl)}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                filterLevel === lvl
                  ? 'bg-indigo-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              {lvl}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Feed List */}
      <div className="space-y-4">
        {filteredAlerts.map((alert) => (
          <div
            key={alert.id}
            className={`p-5 rounded-2xl border transition-all backdrop-blur-xl ${
              alert.level === 'CRITICAL'
                ? 'bg-rose-950/20 border-rose-500/30 hover:border-rose-500/50'
                : alert.level === 'HIGH'
                ? 'bg-orange-950/20 border-orange-500/30 hover:border-orange-500/50'
                : 'bg-slate-900/60 border-white/10 hover:border-white/20'
            }`}
          >
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="flex items-start gap-3.5">
                <div
                  className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 border ${
                    alert.level === 'CRITICAL'
                      ? 'bg-rose-500/20 text-rose-400 border-rose-500/30 shadow-[0_0_10px_rgba(244,63,94,0.3)]'
                      : alert.level === 'HIGH'
                      ? 'bg-orange-500/20 text-orange-400 border-orange-500/30 shadow-[0_0_10px_rgba(249,115,22,0.3)]'
                      : 'bg-amber-500/20 text-amber-300 border-amber-500/30'
                  }`}
                >
                  <AlertTriangle className="w-5 h-5" />
                </div>

                <div>
                  <div className="flex items-center gap-2.5 flex-wrap">
                    <h3 className="text-sm font-bold text-white">{alert.title}</h3>
                    <RiskBadge level={alert.level} size="xs" />
                    <span className="text-xs font-mono font-bold text-indigo-300 bg-indigo-500/10 border border-indigo-500/20 px-2 py-0.5 rounded">
                      {alert.caseId}
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 mt-1 leading-relaxed">{alert.description}</p>
                  <div className="flex items-center gap-3 mt-2 text-[11px] text-slate-400 font-medium">
                    <span>Triggered: {alert.timestamp}</span>
                    {alert.acknowledged && (
                      <span className="text-emerald-400 font-semibold flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Acknowledged ({alert.acknowledgedAt})
                      </span>
                    )}
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-2 flex-shrink-0">
                {!alert.acknowledged ? (
                  <button
                    onClick={() => handleAcknowledge(alert.id)}
                    className="bg-white/5 hover:bg-white/10 text-white text-xs font-bold px-3.5 py-2 rounded-xl border border-white/10 transition-colors flex items-center gap-1"
                  >
                    <Check className="w-4 h-4 text-emerald-400" />
                    <span>Acknowledge</span>
                  </button>
                ) : (
                  <span className="text-xs font-bold text-slate-400 px-3 py-2 bg-white/5 border border-white/5 rounded-xl">
                    Logged
                  </span>
                )}

                <Link
                  to={alert.caseId.startsWith('NHAA') ? `/operator?caseId=${alert.caseId}` : '/operator'}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold px-4 py-2 rounded-xl shadow-[0_0_15px_rgba(99,102,241,0.4)] transition-all flex items-center gap-1"
                >
                  <span>Inspect Case</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default AlertsView
