import React, { createContext, useContext, useState, useEffect } from 'react'

export const LanguageContext = createContext()

export const translations = {
  en: {
    // Brand & Names
    brandName: 'SAHAAY',
    tagline: 'AI-Assisted Early Detection & Dynamic Distress Monitoring',
    supportingStatement: 'Helping identify distress-related signals early and supporting timely human attention.',
    aiDisclaimer: 'AI-assisted screening • Human review required • Not a medical diagnosis',
    integrationNotice: 'Designed for integration with NHAA 14566',
    operatorSubtitle: 'NHAA 14566 — Authorized Operator Portal',
    victimSubtitle: 'NHAA 14566 Support Portal',
    topStripText: 'SIH 2026 PROTOTYPE · DESIGNED FOR INTEGRATION WITH NHAA 14566',

    // Navigation
    navAbout: 'About Us',
    navHowItWorks: 'How It Works',
    navForVictims: 'For Victims',
    navForOperators: 'For Operators',
    navResources: 'Resources',
    getSupport: 'Get Support',
    learnHowItWorks: 'Learn How It Works',

    // General Nav
    skip: 'Skip to main content',
    officerLogin: 'Officer / Counsellor Portal Login',
    home: 'Home',
    citizenPortal: 'Citizen Portal',
    fileGrievance: 'File Grievance',
    trackStatus: 'Track Status',
    emergency: 'Emergency 112',
    pitchDeck: 'Pitch Deck',
    officerConsole: 'Officer Console',
    citizenLogin: 'Citizen Login',
    register: 'Register',
    signOut: 'Sign Out',

    // What Sahaay Does
    whatSahaayDoes: 'What Sahaay Does',
    whatSahaaySubtitle: 'AI-assisted detection and monitoring built with empathy, transparency, and human oversight.',
    card1Title: 'Multilingual Support',
    card1Desc: 'Communicate through supported languages using text or voice.',
    card2Title: 'Early Distress Signals',
    card2Desc: 'AI-assisted identification of distress-related linguistic and emotional signals.',
    card3Title: 'Dynamic Monitoring',
    card3Desc: 'Track changes in vulnerability indicators across interactions.',
    card4Title: 'Human-Centered Support',
    card4Desc: 'AI provides advisory insights while authorized personnel make final decisions.',

    // How Sahaay Works
    howSahaayWorks: 'How Sahaay Works',
    howSahaaySubtitle: 'A structured, explainable six-step workflow ensuring every case receives appropriate care.',
    step1Title: 'LISTEN',
    step1Desc: 'We listen to what you share.',
    step2Title: 'UNDERSTAND',
    step2Desc: 'AI understands context and language.',
    step3Title: 'ASSESS',
    step3Desc: 'AI-assisted assessment of distress-related signals.',
    step4Title: 'EXPLAIN',
    step4Desc: 'Insights are explained clearly.',
    step5Title: 'HUMAN REVIEW',
    step5Desc: 'Authorized personnel review the case.',
    step6Title: 'SUPPORT',
    step6Desc: 'The appropriate support and guidance can follow.',

    // Privacy Section
    privacyTitle: 'Privacy & Security First',
    privacyStatement: 'Your data is safe and confidential. We follow strict security and privacy guidelines.',
    dangerTitle: 'In Immediate Physical Danger?',
    dangerDesc: 'Do not wait for grievance triage. Call 112 (Emergency Dispatch) or 1091 (Women Helpline) immediately.',
    emergencyDir: 'Emergency Directory',

    // Complaint Intake
    intakeBadge: 'Encrypted Intake Channel · NHAA 14566 Integration',
    intakeTitle: 'Submit or Speak Your Grievance',
    intakeDesc: 'Express your situation freely in your own words. Our AI model extracts emotional context and distress markers to assist an authorized case officer.',
    clickToSpeak: 'Click to Speak (Speak Now)',
    listening: 'Listening... Speak naturally in any language or Hinglish',
    micEncrypted: 'Microphone audio is encrypted in transit',
    typeStatement: 'Type or Edit Statement',
    pasteSample: 'Paste Sample English Distress Text →',
    placeholder: 'Type your concern here, or review transcribed text from voice input above...',
    consentText: 'I consent to multimodal acoustic and natural language vulnerability feature extraction for case triage under SAHAAY privacy protocols.',
    submitBtn: 'Submit for Officer Triage',
    docketSuccess: 'Grievance Registered Successfully',
    docketPrompt: 'Your Docket Number',
    docketSub: 'Please save this docket number to track your grievance status on the public portal.',
    trackGrievanceBtn: 'Track Grievance Status →',
    returnHome: 'Return to Home',

    // Track Status
    trackTitle: 'Track Your Grievance Status',
    trackDesc: 'Enter your official docket number (e.g. NHAA/2026/05/2841) to monitor the live review progress.',
    trackPlaceholder: 'e.g. NHAA/2026/05/2841',
    trackButton: 'Track Status',
    quickDockets: 'Quick Demo Dockets:',

    // Citizen Dashboard
    welcome: 'Welcome, Citizen 👋',
    dashboardSub: 'Submit your concern safely, check existing dockets, and access emergency helplines.',
    dashCard1Title: 'Register a Grievance',
    dashCard1Desc: 'Use your voice or type your statement in your language. Our system ensures your voice is heard and safely processed.',
    dashCard2Title: 'Track Grievance Status',
    dashCard2Desc: 'Enter your official docket number to monitor review milestones, assigned department, and resolution timeline.',
    dashCard3Title: 'My Legal Rights',
    dashCard3Desc: 'Read about your statutory protections under the public grievances framework and free NALSA legal aid services.',
    dashCard4Title: 'Emergency Help & Helplines',
    dashCard4Desc: 'Direct hotline access to 112 (Emergency Response), 1091 (Women Helpline), and 14566 (NHAA Toll-Free).'
  },

  hinglish: {
    brandName: 'SAHAAY',
    tagline: 'AI-Assisted Early Detection & Dynamic Distress Monitoring (शीघ्र पहचान एवं तनाव निगरानी)',
    supportingStatement: 'Distress signals ko early stage mein identify karke timely human support provide karna (Helping identify distress-related signals early and supporting timely human attention).',
    aiDisclaimer: 'AI-assisted screening • Human review required • Not a medical diagnosis (चिकित्सीय निदान नहीं)',
    integrationNotice: 'Designed for integration with NHAA 14566',
    operatorSubtitle: 'NHAA 14566 — Authorized Operator Portal (अधिकारी पोर्टल)',
    victimSubtitle: 'NHAA 14566 Support Portal (नागरिक सहायता)',
    topStripText: 'SIH 2026 PROTOTYPE · DESIGNED FOR INTEGRATION WITH NHAA 14566',

    navAbout: 'About Us (हमारे बारे में)',
    navHowItWorks: 'How It Works (कार्यप्रणाली)',
    navForVictims: 'For Victims (पीड़ितों के लिए)',
    navForOperators: 'For Operators (अधिकारियों के लिए)',
    navResources: 'Resources (संसाधन)',
    getSupport: 'Get Support (मदद लें)',
    learnHowItWorks: 'Learn How It Works (जानिए कैसे काम करता है)',

    skip: 'Skip to main content (मुख्य सामग्री)',
    officerLogin: 'Officer Login (अधिकारी लॉगिन)',
    home: 'Home (होम)',
    citizenPortal: 'Citizen Portal (नागरिक पोर्टल)',
    fileGrievance: 'File Grievance (शिकायत दर्ज करें)',
    trackStatus: 'Track Status (स्टेटस चेक करें)',
    emergency: 'Emergency 112 (आपातकालीन 112)',
    pitchDeck: 'Pitch Deck (प्रस्तुति)',
    officerConsole: 'Officer Console (कंसोल)',
    citizenLogin: 'Citizen Login (लॉगिन)',
    register: 'Register (रजिस्टर)',
    signOut: 'Sign Out (लॉग आउट)',

    whatSahaayDoes: 'What Sahaay Does (सहाय क्या करता है)',
    whatSahaaySubtitle: 'AI-assisted detection aur dynamic monitoring jo empathy aur human verification ke saath work karta hai.',
    card1Title: 'Multilingual & Hinglish Support (बहुभाषी व हिंग्लिश)',
    card1Desc: 'Communicate easily in Hindi, English, or Hinglish via speech or text (बोलकर या लिखकर बात करें).',
    card2Title: 'Early Distress Signals (शुरुआती संकट संकेत)',
    card2Desc: 'Linguistic markers aur vocal stress cues ko AI safely analyze karta hai.',
    card3Title: 'Dynamic Monitoring (गतिशील निगरानी)',
    card3Desc: 'Interactions ke through vulnerability trendline track karta hai.',
    card4Title: 'Human-Centered Support (मानव-केंद्रित सहायता)',
    card4Desc: 'AI insights provide karta hai aur trained officer final action lete hain.',

    howSahaayWorks: 'How Sahaay Works (यह कैसे काम करता है)',
    howSahaaySubtitle: '6 simple steps jisme aapki grievance safely process hoti hai.',
    step1Title: 'LISTEN (सुनना)',
    step1Desc: 'We listen carefully to what you share (आपकी बात सुनते हैं).',
    step2Title: 'UNDERSTAND (समझना)',
    step2Desc: 'AI understands context, tone, and Hinglish phrases (संदर्भ समझता है).',
    step3Title: 'ASSESS (आकलन)',
    step3Desc: 'AI-assisted assessment of distress-related signals.',
    step4Title: 'EXPLAIN (स्पष्टीकरण)',
    step4Desc: 'Insights are explained clearly with evidence.',
    step5Title: 'HUMAN REVIEW (अधिकारी समीक्षा)',
    step5Desc: 'Authorized personnel review and verify the case.',
    step6Title: 'SUPPORT (सहायता व राहत)',
    step6Desc: 'Appropriate support and emergency guidance follows.',

    privacyTitle: 'Privacy & Data Security First (गोपनीयता व सुरक्षा)',
    privacyStatement: 'Aapka data 256-bit AES encrypted aur strictly confidential hai. We follow strict security guidelines.',
    dangerTitle: 'Immediate Danger Mein Hain? (In Immediate Physical Danger?)',
    dangerDesc: 'Wait na karein. Immediately 112 (Emergency) ya 1091 (Women Helpline) par call karein.',
    emergencyDir: 'Emergency Directory (हेल्पलाइन लिस्ट)',

    intakeBadge: 'Encrypted Intake Channel · Hinglish & Multimodal Voice',
    intakeTitle: 'Submit or Speak Your Grievance (शिकायत बोलें या लिखें)',
    intakeDesc: 'Apne words mein freely express karein. Hinglish, Hindi ya English mein bole ya type karein.',
    clickToSpeak: 'Click to Speak (बोलने के लिए क्लिक करें)',
    listening: 'Listening... Hinglish ya kisi bhi language mein bolein',
    micEncrypted: 'Microphone audio is encrypted in transit (सुरक्षित ऑडियो)',
    typeStatement: 'Type or Edit Statement (बयान लिखें या बदलें)',
    pasteSample: 'Paste Sample Hinglish Distress Text →',
    placeholder: 'Type your grievance in Hinglish, Hindi or English, ya mic se bole...',
    consentText: 'I consent to multimodal acoustic and natural language analysis under SAHAAY privacy protocols.',
    submitBtn: 'Submit for Officer Triage (अधिकारी समीक्षा हेतु भेजें)',
    docketSuccess: 'Grievance Registered Successfully (शिकायत दर्ज)',
    docketPrompt: 'Your Docket Number (आपका डॉकेट नंबर)',
    docketSub: 'Is docket number ko save karein status track karne ke liye.',
    trackGrievanceBtn: 'Track Grievance Status →',
    returnHome: 'Return to Home (होम पर जाएं)',

    trackTitle: 'Track Your Grievance Status (स्टेटस ट्रैक करें)',
    trackDesc: 'Apna official docket number (e.g. NHAA/2026/05/2841) enter karke live progress check karein.',
    trackPlaceholder: 'e.g. NHAA/2026/05/2841',
    trackButton: 'Track Status (स्टेटस देखें)',
    quickDockets: 'Quick Demo Dockets:',

    welcome: 'Welcome, Citizen 👋 (स्वागत है)',
    dashboardSub: 'Submit concern safely, track dockets, and call emergency helplines.',
    dashCard1Title: 'Register a Grievance (शिकायत दर्ज करें)',
    dashCard1Desc: 'Voice ya text se apni bhasha mein shikayat darj karein.',
    dashCard2Title: 'Track Status (स्थिति ट्रैक करें)',
    dashCard2Desc: 'Docket number enter karke case review milestones check karein.',
    dashCard3Title: 'My Legal Rights (कानूनी अधिकार)',
    dashCard3Desc: 'Free legal aid aur statutory protections ke baare mein jaanein.',
    dashCard4Title: 'Emergency Helplines (आपातकालीन नंबर)',
    dashCard4Desc: '112, 1091 aur 14566 par direct call karein.'
  },

  hi: {
    brandName: 'SAHAAY',
    tagline: 'एआई-सहायक शीघ्र पहचान एवं गतिशील संकट निगरानी (AI-Assisted Early Detection & Dynamic Distress Monitoring)',
    supportingStatement: 'संकट से जुड़े संकेतों की शीघ्र पहचान और समय पर मानवीय सहायता प्रदान करना (Helping identify distress-related signals early and supporting timely human attention).',
    aiDisclaimer: 'एआई-सहायक स्क्रीनिंग • मानवीय समीक्षा अनिवार्य • कोई चिकित्सीय निदान नहीं (AI-assisted screening • Human review required • Not a medical diagnosis)',
    integrationNotice: 'एनएचएए 14566 एकीकरण हेतु डिज़ाइन किया गया (Designed for integration with NHAA 14566)',
    operatorSubtitle: 'एनएचएए 14566 — अधिकृत ऑपरेटर पोर्टल (Authorized Operator Portal)',
    victimSubtitle: 'एनएचएए 14566 सहायता पोर्टल (Support Portal)',
    topStripText: 'एसआईएच 2026 प्रोटोटाइप · एनएचएए 14566 एकीकरण हेतु प्रस्तावित (SIH 2026 Prototype)',

    navAbout: 'हमारे बारे में (About Us)',
    navHowItWorks: 'यह कैसे काम करता है (How It Works)',
    navForVictims: 'पीड़ितों के लिए (For Victims)',
    navForOperators: 'अधिकारियों के लिए (For Operators)',
    navResources: 'संसाधन (Resources)',
    getSupport: 'सहायता प्राप्त करें (Get Support)',
    learnHowItWorks: 'कार्यप्रणाली जानें (Learn How It Works)',

    skip: 'मुख्य सामग्री पर जाएं (Skip to main content)',
    officerLogin: 'अधिकारी पोर्टल लॉगिन (Officer Login)',
    home: 'होम (Home)',
    citizenPortal: 'नागरिक पोर्टल (Citizen Portal)',
    fileGrievance: 'शिकायत दर्ज करें (File Grievance)',
    trackStatus: 'स्थिति ट्रैक करें (Track Status)',
    emergency: 'आपातकालीन 112 (Emergency 112)',
    pitchDeck: 'प्रस्तुति (Pitch Deck)',
    officerConsole: 'अधिकारी कंसोल (Officer Console)',
    citizenLogin: 'नागरिक लॉगिन (Citizen Login)',
    register: 'पंजीकरण (Register)',
    signOut: 'लॉग आउट (Sign Out)',

    whatSahaayDoes: 'सहाय क्या करता है (What Sahaay Does)',
    whatSahaaySubtitle: 'सहानुभूति, पारदर्शिता और मानवीय निगरानी के साथ निर्मित एआई-सहायक पहचान (AI-assisted detection and monitoring built with empathy, transparency, and human oversight).',
    card1Title: 'बहुभाषी सहायता (Multilingual Support)',
    card1Desc: 'टेक्स्ट या आवाज़ का उपयोग करके समर्थित भाषाओं के माध्यम से संवाद करें (Communicate through supported languages using text or voice).',
    card2Title: 'शीघ्र संकट संकेत (Early Distress Signals)',
    card2Desc: 'संकट से जुड़े भाषाई और भावनात्मक संकेतों की एआई-सहायक पहचान (AI-assisted identification of distress-related linguistic and emotional signals).',
    card3Title: 'गतिशील निगरानी (Dynamic Monitoring)',
    card3Desc: 'विभिन्न इंटरैक्शन में भेद्यता संकेतकों में होने वाले परिवर्तनों को ट्रैक करें (Track changes in vulnerability indicators across interactions).',
    card4Title: 'मानव-केंद्रित सहायता (Human-Centered Support)',
    card4Desc: 'एआई सलाहकार अंतर्दृष्टि प्रदान करता है जबकि अधिकृत कर्मी अंतिम निर्णय लेते हैं (AI provides advisory insights while authorized personnel make final decisions).',

    howSahaayWorks: 'सहाय कैसे काम करता है (How Sahaay Works)',
    howSahaaySubtitle: 'एक संरचित, व्याख्यात्मक छह-चरणीय कार्यप्रवाह (A structured, explainable six-step workflow).',
    step1Title: '01. सुनना (LISTEN)',
    step1Desc: 'आप जो साझा करते हैं हम उसे ध्यान से सुनते हैं (We listen to what you share).',
    step2Title: '02. समझना (UNDERSTAND)',
    step2Desc: 'एआई संदर्भ और भाषा को समझता है (AI understands context and language).',
    step3Title: '03. मूल्यांकन (ASSESS)',
    step3Desc: 'संकट से जुड़े संकेतों का एआई-सहायक मूल्यांकन (AI-assisted assessment of distress-related signals).',
    step4Title: '04. स्पष्टीकरण (EXPLAIN)',
    step4Desc: 'अंतर्दृष्टि स्पष्ट रूप से समझाई जाती है (Insights are explained clearly).',
    step5Title: '05. मानवीय समीक्षा (HUMAN REVIEW)',
    step5Desc: 'अधिकृत कर्मी मामले की समीक्षा करते हैं (Authorized personnel review the case).',
    step6Title: '06. सहायता (SUPPORT)',
    step6Desc: 'उचित सहायता और मार्गदर्शन प्रदान किया जाता है (The appropriate support and guidance can follow).',

    privacyTitle: 'गोपनीयता और सुरक्षा सर्वोपरि (Privacy & Security First)',
    privacyStatement: 'आपका डेटा सुरक्षित और गोपनीय है (Your data is safe and confidential. We follow strict security and privacy guidelines).',
    dangerTitle: 'क्या आप तत्काल शारीरिक खतरे में हैं? (In Immediate Danger?)',
    dangerDesc: 'प्रतीक्षा न करें। तुरंत 112 या 1091 पर कॉल करें (Call 112 or 1091 immediately).',
    emergencyDir: 'आपातकालीन निर्देशिका (Emergency Directory)',

    intakeBadge: 'एन्क्रिप्टेड शिकायत चैनल (Encrypted Intake Channel · NHAA 14566)',
    intakeTitle: 'अपनी शिकायत बोलें या दर्ज करें (Submit or Speak Your Grievance)',
    intakeDesc: 'अपनी स्थिति को अपने शब्दों में खुलकर व्यक्त करें (Express your situation freely in your own words).',
    clickToSpeak: 'बोलने के लिए क्लिक करें (Click to Speak / Speak Now)',
    listening: 'सुन रहे हैं... बोलें (Listening... Speak naturally in any language / Hinglish)',
    micEncrypted: 'माइक्रोफ़ोन ऑडियो एन्क्रिप्टेड है (Microphone audio is encrypted in transit)',
    typeStatement: 'बयान लिखें या संपादित करें (Type or Edit Statement)',
    pasteSample: 'नमूना हिंदी संकट पाठ पेस्ट करें (Paste Sample Hindi Distress Text) →',
    placeholder: 'अपनी चिंता यहाँ लिखें, या ऊपर दिए गए वॉइस इनपुट से बोले गए टेक्स्ट की समीक्षा करें...',
    consentText: 'मैं सहाय गोपनीयता प्रोटोकॉल के तहत डेटा विश्लेषण की सहमति देता/देती हूँ (I consent to privacy protocols).',
    submitBtn: 'अधिकारी समीक्षा के लिए जमा करें (Submit for Officer Triage)',
    docketSuccess: 'शिकायत सफलतापूर्वक दर्ज (Grievance Registered Successfully)',
    docketPrompt: 'आपका डॉकेट नंबर (Your Docket Number)',
    docketSub: 'स्थिति ट्रैक करने के लिए यह डॉकेट नंबर सुरक्षित रखें (Save this docket number to track your grievance).',
    trackGrievanceBtn: 'शिकायत की स्थिति ट्रैक करें (Track Grievance Status) →',
    returnHome: 'होम पेज पर लौटें (Return to Home)',

    trackTitle: 'अपनी शिकायत की स्थिति ट्रैक करें (Track Your Grievance Status)',
    trackDesc: 'लाइव प्रगति देखने के लिए अपना डॉकेट नंबर दर्ज करें (Enter your docket number to monitor live review progress).',
    trackPlaceholder: 'उदा. NHAA/2026/05/2841',
    trackButton: 'स्थिति ट्रैक करें (Track Status)',
    quickDockets: 'त्वरित डेमो डॉकेट्स (Quick Demo Dockets):',

    welcome: 'स्वागत है, नागरिक 👋 (Welcome, Citizen)',
    dashboardSub: 'अपनी समस्या सुरक्षित रूप से दर्ज करें और सहायता प्राप्त करें (Submit your concern safely).',
    dashCard1Title: 'शिकायत दर्ज करें (Register a Grievance)',
    dashCard1Desc: 'अपनी आवाज़ का उपयोग करें या अपनी भाषा में बयान टाइप करें (Use your voice or type your statement).',
    dashCard2Title: 'स्थिति ट्रैक करें (Track Grievance Status)',
    dashCard2Desc: 'समीक्षा चरणों और समयरेखा की निगरानी करें (Monitor review milestones and resolution timeline).',
    dashCard3Title: 'मेरे कानूनी अधिकार (My Legal Rights)',
    dashCard3Desc: 'मुफ्त नालसा कानूनी सहायता और सुरक्षा के बारे में जानें (Read about statutory protections and legal aid).',
    dashCard4Title: 'आपातकालीन हेल्पलाइन (Emergency Helplines)',
    dashCard4Desc: '112, 1091 और 14566 पर त्वरित संपर्क (Direct hotline access).'
  },

  mr: {
    brandName: 'SAHAAY',
    tagline: 'AI-सहाय्यित लवकर शोध आणि गतिमान संकट देखरेख (AI-Assisted Early Detection & Dynamic Distress Monitoring)',
    supportingStatement: 'संकटाशी संबंधित संकेतांची लवकर ओळख आणि वेळेवर मानवी लक्ष देणे (Helping identify distress-related signals early).',
    aiDisclaimer: 'AI-सहाय्यित तपासणी • मानवी पुनरावलोकन आवश्यक • वैद्यकीय निदान नाही (AI-assisted screening • Human review required)',
    integrationNotice: 'NHAA १४५६६ सह एकत्रीकरणासाठी डिझाइन केलेले (Designed for integration with NHAA 14566)',
    operatorSubtitle: 'NHAA १४५६६ — अधिकृत ऑपरेटर पोर्टल (Authorized Operator Portal)',
    victimSubtitle: 'NHAA १४५६६ सहाय्यता पोर्टल (Support Portal)',
    topStripText: 'SIH २०२६ प्रोटोटाइप · NHAA १४५६६ सह एकत्रीकरणासाठी डिझाइन केलेले (SIH 2026 Prototype)',

    navAbout: 'आमच्याबद्दल (About Us)',
    navHowItWorks: 'कसे कार्य करते (How It Works)',
    navForVictims: 'पीडितांसाठी (For Victims)',
    navForOperators: 'ऑपरेटरसाठी (For Operators)',
    navResources: 'संसाधने (Resources)',
    getSupport: 'मदत मिळवा (Get Support)',
    learnHowItWorks: 'कार्यपद्धती जाणून घ्या (Learn How It Works)',

    skip: 'मुख्य सामग्रीकडे जा (Skip to main content)',
    officerLogin: 'अधिकारी पोर्टल लॉगिन (Officer Login)',
    home: 'मुख्यपृष्ठ (Home)',
    citizenPortal: 'नागरिक पोर्टल (Citizen Portal)',
    fileGrievance: 'तक्रार नोंदवा (File Grievance)',
    trackStatus: 'स्थिती तपासा (Track Status)',
    emergency: 'आपत्कालीन ११२ (Emergency 112)',
    pitchDeck: 'सादरीकरण (Pitch Deck)',
    officerConsole: 'अधिकारी कन्सोल (Officer Console)',
    citizenLogin: 'नागरिक लॉगिन (Citizen Login)',
    register: 'नोंदणी करा (Register)',
    signOut: 'बाहेर पडा (Sign Out)',

    whatSahaayDoes: 'सहाय्य काय करते (What Sahaay Does)',
    whatSahaaySubtitle: 'सहानुभूती, पारदर्शकता आणि मानवी देखरेखीसह AI-सहाय्यित शोध आणि देखरेख (AI-assisted detection and monitoring).',
    card1Title: 'बहुभाषिक समर्थन (Multilingual Support)',
    card1Desc: 'मजकूर किंवा आवाज वापरून समर्थित भाषांद्वारे संवाद साधा (Communicate using text or voice).',
    card2Title: 'लवकर संकट संकेत (Early Distress Signals)',
    card2Desc: 'संकटाशी संबंधित भाषिक आणि भावनिक संकेतांची AI-सहाय्यित ओळख (AI-assisted identification of signals).',
    card3Title: 'गतिमान देखरेख (Dynamic Monitoring)',
    card3Desc: 'संवादांमधील असुरक्षितता निर्देशकांमधील बदलांचा मागोवा घ्या (Track changes in vulnerability indicators).',
    card4Title: 'मानव-केंद्रित समर्थन (Human-Centered Support)',
    card4Desc: 'AI सल्लागार अंतर्दृष्टी प्रदान करते तर अधिकृत कर्मचारी अंतिम निर्णय घेतात (AI provides advisory insights).',

    howSahaayWorks: 'सहाय्य कसे कार्य करते (How Sahaay Works)',
    howSahaaySubtitle: 'प्रत्येक प्रकरणाला योग्य काळजी मिळावी यासाठी एक संरचित सहा-चरणांची प्रक्रिया (A structured six-step workflow).',
    step1Title: '01. ऐकणे (LISTEN)',
    step1Desc: 'तुम्ही जे सांगता ते आम्ही ऐकतो (We listen to what you share).',
    step2Title: '02. समजून घेणे (UNDERSTAND)',
    step2Desc: 'AI संदर्भ आणि भाषा समजून घेते (AI understands context and language).',
    step3Title: '03. मूल्यांकन (ASSESS)',
    step3Desc: 'संकट संकेतांचे AI-सहाय्यित मूल्यांकन (AI-assisted assessment of distress signals).',
    step4Title: '04. स्पष्टीकरण (EXPLAIN)',
    step4Desc: 'निष्कर्ष स्पष्टपणे समजावून सांगितले जातात (Insights are explained clearly).',
    step5Title: '05. मानवी पुनरावलोकन (HUMAN REVIEW)',
    step5Desc: 'अधिकृत कर्मचारी प्रकरणाचे पुनरावलोकन करतात (Authorized personnel review the case).',
    step6Title: '06. सहाय्यता (SUPPORT)',
    step6Desc: 'योग्य सहाय्य आणि मार्गदर्शन केले जाते (The appropriate support and guidance follows).',

    privacyTitle: 'गोपनीयता आणि सुरक्षा (Privacy & Security First)',
    privacyStatement: 'तुमचा डेटा सुरक्षित आणि गोपनीय आहे (Your data is safe and confidential).',
    dangerTitle: 'तात्काळ शारीरिक धोक्यात आहात का? (In Immediate Danger?)',
    dangerDesc: 'त्वरित ११२ किंवा १०९१ वर कॉल करा (Call 112 or 1091 immediately).',
    emergencyDir: 'आपत्कालीन निर्देशिका (Emergency Directory)',

    intakeBadge: 'एन्क्रिप्टेड चॅनल (Encrypted Intake Channel · NHAA 14566)',
    intakeTitle: 'आपली तक्रार बोला किंवा नोंदवा (Submit or Speak Your Grievance)',
    intakeDesc: 'आपली परिस्थिती आपल्या शब्दात मोकळेपणाने मांडा (Express your situation freely in your own words).',
    clickToSpeak: 'बोलण्यासाठी क्लिक करा (Click to Speak / Speak Now)',
    listening: 'ऐकत आहे... बोला (Listening... Speak naturally in any language / Hinglish)',
    micEncrypted: 'मायक्रोफोन ऑडिओ एन्क्रिप्टेड आहे (Microphone audio is encrypted in transit)',
    typeStatement: 'मजकूर लिहा किंवा संपादित करा (Type or Edit Statement)',
    pasteSample: 'मराठी नमुना मजकूर जोडा (Paste Sample Marathi Text) →',
    placeholder: 'आपली तक्रार येथे टाइप करा...',
    consentText: 'मी सहाय्य गोपनीयता नियमांनुसार संमती देतो/देते (I consent to privacy protocols).',
    submitBtn: 'अधिकारी पुनरावलोकनासाठी पाठवा (Submit for Officer Triage)',
    docketSuccess: 'तक्रार यशस्वीरित्या नोंदवली (Grievance Registered Successfully)',
    docketPrompt: 'आपला डॉकेट क्रमांक (Your Docket Number)',
    docketSub: 'स्थिती तपासण्यासाठी हा क्रमांक जतन करा (Save this docket number).',
    trackGrievanceBtn: 'तक्रार स्थिती तपासा (Track Grievance Status) →',
    returnHome: 'मुख्यपृष्ठावर परत या (Return to Home)',

    trackTitle: 'आपल्या तक्रारीची स्थिती तपासा (Track Your Grievance Status)',
    trackDesc: 'प्रगती पाहण्यासाठी आपला डॉकेट क्रमांक प्रविष्ट करा (Enter your docket number).',
    trackPlaceholder: 'उदा. NHAA/2026/05/2841',
    trackButton: 'स्थिती तपासा (Track Status)',
    quickDockets: 'डेमो डॉकेट्स (Demo Dockets):',

    welcome: 'स्वागत आहे, नागरिक 👋 (Welcome, Citizen)',
    dashboardSub: 'तक्रार नोंदवा आणि आपत्कालीन सेवा मिळवा (Submit concern safely).',
    dashCard1Title: 'तक्रार नोंदवा (Register a Grievance)',
    dashCard1Desc: 'आपल्या भाषेत बोला किंवा लिहा (Use your voice or type).',
    dashCard2Title: 'तक्रार स्थिती तपासा (Track Status)',
    dashCard2Desc: 'सद्यस्थिती आणि निवारण जाणून घ्या (Monitor milestones).',
    dashCard3Title: 'माझे कायदेशीर हक्क (My Legal Rights)',
    dashCard3Desc: 'मोफत विधी सेवा आणि हक्कांविषयी माहिती (Free legal aid services).',
    dashCard4Title: 'आपत्कालीन हेल्पलाइन (Emergency Helplines)',
    dashCard4Desc: '११२, १०९१ आणि १४५६६ वर तात्काळ संपर्क (Direct hotline access).'
  },

  ta: {
    brandName: 'SAHAAY',
    tagline: 'AI-உதவி ஆரம்பகால கண்டறிதல் மற்றும் மாறும் இடர் கண்காணிப்பு (AI-Assisted Early Detection & Dynamic Distress Monitoring)',
    supportingStatement: 'துன்பம் தொடர்பான சிக்னல்களை முன்கூட்டியே கண்டறிந்து மனித கவனத்தை ஆதரித்தல் (Helping identify distress signals early).',
    aiDisclaimer: 'AI-உதவி திரையிடல் • மனித மறுஆய்வு தேவை • மருத்துவ நோயறிதல் அல்ல (AI-assisted screening • Human review required)',
    integrationNotice: 'NHAA 14566 உடன் ஒருங்கிணைக்க வடிவமைக்கப்பட்டது (Designed for integration with NHAA 14566)',
    operatorSubtitle: 'NHAA 14566 — அங்கீகரிக்கப்பட்ட அதிகாரி தளம் (Authorized Operator Portal)',
    victimSubtitle: 'NHAA 14566 ஆதரவு தளம் (Support Portal)',
    topStripText: 'SIH 2026 மாதிரி வடிவம் · NHAA 14566 இணைப்புக்காக வடிவமைக்கப்பட்டது (SIH 2026 Prototype)',

    navAbout: 'எங்களைப் பற்றி (About Us)',
    navHowItWorks: 'எப்படி வேலை செய்கிறது (How It Works)',
    navForVictims: 'பாதிக்கப்பட்டோருக்கு (For Victims)',
    navForOperators: 'அதிகாரிகளுக்கு (For Operators)',
    navResources: 'வளங்கள் (Resources)',
    getSupport: 'ஆதரவு பெறுக (Get Support)',
    learnHowItWorks: 'செயல்பாட்டை அறிக (Learn How It Works)',

    skip: 'முக்கிய பகுதிக்குச் செல்லவும் (Skip to main content)',
    officerLogin: 'அதிகாரி உள்நுழைவு (Officer Login)',
    home: 'முகப்பு (Home)',
    citizenPortal: 'குடிமக்கள் தளம் (Citizen Portal)',
    fileGrievance: 'புகார் பதிவு செய் (File Grievance)',
    trackStatus: 'நிலை சரிபார்க்கவும் (Track Status)',
    emergency: 'அவசரம் 112 (Emergency 112)',
    pitchDeck: 'விளக்கக்காட்சி (Pitch Deck)',
    officerConsole: 'அதிகாரி பணியகம் (Officer Console)',
    citizenLogin: 'குடிமக்கள் உள்நுழைவு (Citizen Login)',
    register: 'பதிவு செய்க (Register)',
    signOut: 'வெளியேறு (Sign Out)',

    whatSahaayDoes: 'சஹாய் என்ன செய்கிறது (What Sahaay Does)',
    whatSahaaySubtitle: 'மனித மேற்பார்வையுடன் கூடிய ஆரம்பகால இடர் கண்டறிதல் (AI-assisted detection and monitoring).',
    card1Title: 'பன்மொழி ஆதரவு (Multilingual Support)',
    card1Desc: 'உங்கள் தாய்மொழியில் பேசி அல்லது தட்டச்சு செய்து தொடர்பு கொள்ளுங்கள் (Communicate using text or voice).',
    card2Title: 'ஆரம்பகால இடர் சிக்னல்கள் (Early Distress Signals)',
    card2Desc: 'துன்பம் தொடர்பான உணர்ச்சி சிக்னல்களை AI கண்டறியும் (AI-assisted identification of distress signals).',
    card3Title: 'தொடர் கண்காணிப்பு (Dynamic Monitoring)',
    card3Desc: 'இடர் நிலையின் மாற்றங்களைத் துல்லியமாகக் கண்காணிக்கும் (Track changes in vulnerability indicators).',
    card4Title: 'மனித மைய ஆதரவு (Human-Centered Support)',
    card4Desc: 'அதிகாரிகள் இறுதி முடிவுகளை எடுக்கும் வகையில் AI ஆலோசனை வழங்குகிறது (AI provides advisory insights).',

    howSahaayWorks: 'சஹாய் செயல்படும் விதம் (How Sahaay Works)',
    howSahaaySubtitle: 'ஒவ்வொரு வழக்கிற்கும் தகுந்த கவனம் கிடைக்க உதவும் ஆறு படிகள் (A structured six-step workflow).',
    step1Title: '01. கேட்டல் (LISTEN)',
    step1Desc: 'நீங்கள் பகிர்வதை நாங்கள் கேட்கிறோம் (We listen to what you share).',
    step2Title: '02. புரிதல் (UNDERSTAND)',
    step2Desc: 'AI சூழலையும் மொழியையும் புரிந்துகொள்கிறது (AI understands context and language).',
    step3Title: '03. மதிப்பீடு (ASSESS)',
    step3Desc: 'துன்ப சிக்னல்களை AI மதிப்பீடு செய்கிறது (AI-assisted assessment of signals).',
    step4Title: '04. விளக்கம் (EXPLAIN)',
    step4Desc: 'விவரங்கள் தெளிவாக விளக்கப்படுகின்றன (Insights are explained clearly).',
    step5Title: '05. மனித மறுஆய்வு (HUMAN REVIEW)',
    step5Desc: 'அங்கீகரிக்கப்பட்ட அதிகாரி மதிப்பாய்வு செய்கிறார் (Authorized personnel review the case).',
    step6Title: '06. ஆதரவு (SUPPORT)',
    step6Desc: 'சரியான ஆதரவும் வழிகாட்டலும் வழங்கப்படுகிறது (Appropriate support and guidance follows).',

    privacyTitle: 'தனியுரிமை மற்றும் பாதுகாப்பு (Privacy & Security First)',
    privacyStatement: 'உங்கள் தரவு பாதுகாப்பானது மற்றும் ரகசியமானது (Your data is safe and confidential).',
    dangerTitle: 'உடனடி ஆபத்தில் உள்ளீர்களா? (In Immediate Danger?)',
    dangerDesc: 'உடனடியாக 112 அல்லது 1091 எண்ணை அழைக்கவும் (Call 112 or 1091 immediately).',
    emergencyDir: 'அவசர எண்கள் (Emergency Directory)',

    intakeBadge: 'பாதுகாப்பான சேனல் (Encrypted Channel · NHAA 14566)',
    intakeTitle: 'உங்கள் புகாரைப் பதிவு செய்யவும் (Submit or Speak Your Grievance)',
    intakeDesc: 'உங்கள் புகாரை உங்கள் சொந்த வார்த்தைகளில் வெளிப்படுத்துங்கள் (Express your situation freely).',
    clickToSpeak: 'பேச கிளிக் செய்யவும் (Click to Speak / Speak Now)',
    listening: 'கேட்கிறது... பேசுங்கள் (Listening... Speak in any language / Hinglish)',
    micEncrypted: 'ஆடியோ குறியாக்கம் செய்யப்படுகிறது (Audio encrypted in transit)',
    typeStatement: 'புகாரை எழுதவும் (Type or Edit Statement)',
    pasteSample: 'மாதிரி உரையை ஒட்டவும் (Paste Sample Text) →',
    placeholder: 'உங்கள் புகாரை இங்கே தட்டச்சு செய்யவும்...',
    consentText: 'நான் தனியுரிமை நெறிமுறைகளுக்கு ஒப்புக்கொள்கிறேன் (I consent to privacy protocols).',
    submitBtn: 'அதிகாரி ஆய்வுக்கு அனுப்பவும் (Submit for Officer Triage)',
    docketSuccess: 'புகார் வெற்றிகரமாகப் பதிவு செய்யப்பட்டது (Grievance Registered Successfully)',
    docketPrompt: 'உங்கள் ஆவண எண் (Your Docket Number)',
    docketSub: 'நிலையைக் கண்காணிக்க இந்த எண்ணைச் சேமிக்கவும் (Save this docket number).',
    trackGrievanceBtn: 'நிலையைக் காண்க (Track Grievance Status) →',
    returnHome: 'முகப்புக்குச் செல்லவும் (Return to Home)',

    trackTitle: 'புகார் நிலையைத் தெரிந்துகொள்ளவும் (Track Grievance Status)',
    trackDesc: 'முன்னேற்றத்தைக் கண்காணிக்க ஆவண எண்ணை உள்ளிடவும் (Enter docket number).',
    trackPlaceholder: 'எ.கா. NHAA/2026/05/2841',
    trackButton: 'நிலையைக் காண்க (Track Status)',
    quickDockets: 'மாதிரி எண்கள் (Demo Dockets):',

    welcome: 'வணக்கம், குடிமக்களே 👋 (Welcome, Citizen)',
    dashboardSub: 'புகார் பதிவு செய்யவும் மற்றும் அவசர உதவிகளைப் பெறவும் (Submit concern safely).',
    dashCard1Title: 'புகார் பதிவு செய் (Register a Grievance)',
    dashCard1Desc: 'பேசி அல்லது தட்டச்சு செய்து புகாரைப் பதியுங்கள் (Use voice or text).',
    dashCard2Title: 'புகார் நிலையை அறியவும் (Track Status)',
    dashCard2Desc: 'தீர்வு நிலையை எளிதாகக் கண்காணிக்கலாம் (Monitor milestones).',
    dashCard3Title: 'என் சட்ட உரிமைகள் (My Legal Rights)',
    dashCard3Desc: 'இலவச சட்ட உதவி பற்றிய வழிகாட்டல் (Free legal aid services).',
    dashCard4Title: 'அவசர உதவி எண்கள் (Emergency Helplines)',
    dashCard4Desc: '112, 1091 மற்றும் 14566 எண்களுக்கு உடனடி இணைப்பு (Direct hotline access).'
  },

  bn: {
    brandName: 'SAHAAY',
    tagline: 'এআই-সহায়তাপ্রাপ্ত প্রাথমিক সনাক্তকরণ ও সংকট পর্যবেক্ষণ (AI-Assisted Early Detection & Dynamic Distress Monitoring)',
    supportingStatement: 'সংকট সম্পর্কিত লক্ষণগুলি দ্রুত সনাক্তকরণ এবং সময়মতো মানবিক সহায়তা প্রদান (Helping identify distress-related signals early).',
    aiDisclaimer: 'এআই-সহায়তাপ্রাপ্ত স্ক্রীনিং • মানব পর্যালোচনা আবশ্যক • কোনো চিকিৎসা নির্ণয় নয় (AI-assisted screening • Human review required)',
    integrationNotice: 'NHAA ১৪৫৬৬ এর সাথে সংহতকরণের জন্য ডিজাইন করা হয়েছে (Designed for integration with NHAA 14566)',
    operatorSubtitle: 'NHAA ১৪৫৬৬ — অনুমোদিত অপারেটর পোর্টাল (Authorized Operator Portal)',
    victimSubtitle: 'NHAA ১৪৫৬৬ সহায়তা পোর্টাল (Support Portal)',
    topStripText: 'SIH ২০২৬ প্রোটোটাইপ · NHAA ১৪৫৬৬ এর সাথে সংহতকরণের জন্য ডিজাইন করা হয়েছে (SIH 2026 Prototype)',

    navAbout: 'আমাদের সম্পর্কে (About Us)',
    navHowItWorks: 'কীভাবে কাজ করে (How It Works)',
    navForVictims: 'ভিকটিমদের জন্য (For Victims)',
    navForOperators: 'অপারেটরদের জন্য (For Operators)',
    navResources: 'রিসোর্স (Resources)',
    getSupport: 'সহায়তা নিন (Get Support)',
    learnHowItWorks: 'পদ্ধতি জানুন (Learn How It Works)',

    skip: 'মূল অংশে যান (Skip to main content)',
    officerLogin: 'অফিসার লগইন (Officer Login)',
    home: 'হোম (Home)',
    citizenPortal: 'নাগরিক পোর্টাল (Citizen Portal)',
    fileGrievance: 'অভিযোগ দায়ের করুন (File Grievance)',
    trackStatus: 'স্থিতি ট্র্যাক করুন (Track Status)',
    emergency: 'জরুরী ১১২ (Emergency 112)',
    pitchDeck: 'প্রেজেন্টেশন (Pitch Deck)',
    officerConsole: 'অফিসার কনসোল (Officer Console)',
    citizenLogin: 'নাগরিক লগইন (Citizen Login)',
    register: 'নিবন্ধন করুন (Register)',
    signOut: 'লগ আউট (Sign Out)',

    whatSahaayDoes: 'সহায় কী করে (What Sahaay Does)',
    whatSahaaySubtitle: 'সহানুভূতি, স্বচ্ছতা এবং মানবিক তত্ত্বাবধানের সাথে এআই-সহায়তাপ্রাপ্ত নজরদারি (AI-assisted detection and monitoring).',
    card1Title: 'বহুভাষিক সমর্থন (Multilingual Support)',
    card1Desc: 'টেক্সট বা ভয়েস ব্যবহার করে আপনার ভাষায় যোগাযোগ করুন (Communicate using text or voice).',
    card2Title: 'প্রাথমিক সংকট লক্ষণ (Early Distress Signals)',
    card2Desc: 'সংকটপূর্ণ মানসিক লক্ষণগুলির এআই সনাক্তকরণ (AI-assisted identification of signals).',
    card3Title: 'গতিশীল পর্যবেক্ষণ (Dynamic Monitoring)',
    card3Desc: 'ঝুঁকির সূচকে পরিবর্তনের উপর নজর রাখুন (Track changes in vulnerability indicators).',
    card4Title: 'মানব-কেন্দ্রিক সহায়তা (Human-Centered Support)',
    card4Desc: 'এআই অন্তর্দৃষ্টি দেয় আর কর্মকর্তা সিদ্ধান্ত নেন (AI provides advisory insights).',

    howSahaayWorks: 'সহায় কীভাবে কাজ করে (How Sahaay Works)',
    howSahaaySubtitle: 'প্রতিটি মামলার সঠিক মূল্যায়নের জন্য ছয়টি পদক্ষেপের কাঠামো (A structured six-step workflow).',
    step1Title: '01. শোনা (LISTEN)',
    step1Desc: 'আমরা আপনার কথা মনোযোগ দিয়ে শুনি (We listen to what you share).',
    step2Title: '02. বোঝা (UNDERSTAND)',
    step2Desc: 'এআই প্রেক্ষাপট ও ভাষা বোঝে (AI understands context and language).',
    step3Title: '03. মূল্যায়ন (ASSESS)',
    step3Desc: 'সংকট সংকেতের এআই মূল্যায়ন (AI-assisted assessment of signals).',
    step4Title: '04. ব্যাখ্যা (EXPLAIN)',
    step4Desc: 'বিশ্লেষণ স্পষ্টভাবে ব্যাখ্যা করা হয় (Insights are explained clearly).',
    step5Title: '05. মানব পর্যালোচনা (HUMAN REVIEW)',
    step5Desc: 'অনুমোদিত কর্মকর্তা পর্যালোচনা করেন (Authorized personnel review the case).',
    step6Title: '06. সহায়তা (SUPPORT)',
    step6Desc: 'উপযুক্ত সহায়তা প্রদান করা হয় (Appropriate support and guidance follows).',

    privacyTitle: 'গোপনীয়তা ও নিরাপত্তা প্রথম (Privacy & Security First)',
    privacyStatement: 'আপনার ডেটা নিরাপদ ও গোপনীয় (Your data is safe and confidential).',
    dangerTitle: 'আপনি কি তাৎক্ষণিক বিপদে আছেন? (In Immediate Danger?)',
    dangerDesc: 'অবিলম্বে ১১২ বা ১০৯১ নম্বরে কল করুন (Call 112 or 1091 immediately).',
    emergencyDir: 'জরুরী ডিরেক্টরি (Emergency Directory)',

    intakeBadge: 'এনক্রিপ্ট করা চ্যানেল (Encrypted Channel · NHAA 14566)',
    intakeTitle: 'আপনার অভিযোগ বলুন বা লিখুন (Submit or Speak Your Grievance)',
    intakeDesc: 'আপনার পরিস্থিতি নিজের ভাষায় বর্ণনা করুন (Express your situation freely in your own words).',
    clickToSpeak: 'বলতে ক্লিক করুন (Click to Speak / Speak Now)',
    listening: 'শুনছি... বলুন (Listening... Speak in any language / Hinglish)',
    micEncrypted: 'মাইক্রোফোন অডিও সম্পূর্ণ সুরক্ষিত (Microphone audio is encrypted in transit)',
    typeStatement: 'বিবৃতি লিখুন বা সম্পাদনা করুন (Type or Edit Statement)',
    pasteSample: 'বাংলা নমুনা পাঠ্য পেস্ট করুন (Paste Sample Text) →',
    placeholder: 'আপনার অভিযোগ এখানে লিখুন...',
    consentText: 'আমি ডেটা প্রক্রিয়াকরণে সম্মতি দিচ্ছি (I consent to privacy protocols).',
    submitBtn: 'পর্যালোচনার জন্য জমা দিন (Submit for Officer Triage)',
    docketSuccess: 'অভিযোগ সফলভাবে নথিভুক্ত (Grievance Registered Successfully)',
    docketPrompt: 'আপনার ডকেট নম্বর (Your Docket Number)',
    docketSub: 'স্থিতি ট্র্যাক করতে এই নম্বরটি সংরক্ষণ করুন (Save this docket number).',
    trackGrievanceBtn: 'অভিযোগের স্থিতি ট্র্যাক করুন (Track Grievance Status) →',
    returnHome: 'হোমে ফিরে যান (Return to Home)',

    trackTitle: 'অভিযোগের স্থিতি ট্র্যাক করুন (Track Grievance Status)',
    trackDesc: 'অগ্রগতি দেখতে ডকেট নম্বর লিখুন (Enter your docket number).',
    trackPlaceholder: 'যেমন: NHAA/2026/05/2841',
    trackButton: 'স্থিতি ট্র্যাক করুন (Track Status)',
    quickDockets: 'নমুনা ডকেট (Demo Dockets):',

    welcome: 'স্বাগতম, নাগরিক 👋 (Welcome, Citizen)',
    dashboardSub: 'নিরাপদে অভিযোগ নথিভুক্ত করুন এবং সহায়তা পান (Submit concern safely).',
    dashCard1Title: 'অভিযোগ দায়ের করুন (Register a Grievance)',
    dashCard1Desc: 'আপনার ভাষায় বলুন বা লিখুন (Use your voice or type).',
    dashCard2Title: 'স্থিতি ট্র্যাক করুন (Track Status)',
    dashCard2Desc: 'সমাধানের অগ্রগতি পর্যবেক্ষণ করুন (Monitor milestones).',
    dashCard3Title: 'আমার আইনি অধিকার (My Legal Rights)',
    dashCard3Desc: 'বিনামূল্যে আইনি সহায়তা ও সুরক্ষা (Free legal aid services).',
    dashCard4Title: 'জরুরী হেল্পলাইন (Emergency Helplines)',
    dashCard4Desc: '১১২, ১০৯১ এবং ১৪৫৬৬ নম্বরে সরাসরি যোগাযোগ (Direct hotline access).'
  },

  te: {
    brandName: 'SAHAAY',
    tagline: 'AI-సహాయక ప్రారంభ గుర్తింపు & డైనమిక్ బాధ పర్యవేక్షణ (AI-Assisted Early Detection & Dynamic Distress Monitoring)',
    supportingStatement: 'ప్రమాద సంకేతాలను ముందుగానే గుర్తించి సకాలంలో మానవ సహాయాన్ని అందించడం (Helping identify distress-related signals early).',
    aiDisclaimer: 'AI-సహాయక స్క్రీనింగ్ • మానవ సమీక్ష తప్పనిసరి • వైద్య నిర్ధారణ కాదు (AI-assisted screening • Human review required)',
    integrationNotice: 'NHAA 14566 అనుసంధానం కోసం రూపొందించబడింది (Designed for integration with NHAA 14566)',
    operatorSubtitle: 'NHAA 14566 — అధీకృత ఆపరేటర్ పోర్టల్ (Authorized Operator Portal)',
    victimSubtitle: 'NHAA 14566 మద్దతు పోర్టల్ (Support Portal)',
    topStripText: 'SIH 2026 ప్రోటోటైప్ · NHAA 14566 అనుసంధానం కోసం రూపొందించబడింది (SIH 2026 Prototype)',

    navAbout: 'మా గురించి (About Us)',
    navHowItWorks: 'ఎలా పని చేస్తుంది (How It Works)',
    navForVictims: 'బాధితులకు (For Victims)',
    navForOperators: 'ఆపరేటర్లకు (For Operators)',
    navResources: 'వనరులు (Resources)',
    getSupport: 'సహాయం పొందండి (Get Support)',
    learnHowItWorks: 'విధానం తెలుసుకోండి (Learn How It Works)',

    skip: 'ప్రధాన కంటెంట్‌కు వెళ్లండి (Skip to main content)',
    officerLogin: 'అధికారి లాగిన్ (Officer Login)',
    home: 'హోమ్ (Home)',
    citizenPortal: 'పౌర పోర్టల్ (Citizen Portal)',
    fileGrievance: 'ఫిర్యాదు దాఖలు చేయండి (File Grievance)',
    trackStatus: 'స్థితిని ట్రాక్ చేయండి (Track Status)',
    emergency: 'అత్యవసర 112 (Emergency 112)',
    pitchDeck: 'ప్రజెంటేషన్ (Pitch Deck)',
    officerConsole: 'అధికారి కన్సోల్ (Officer Console)',
    citizenLogin: 'సిటిజన్ లాగిన్ (Citizen Login)',
    register: 'నమోదు చేసుకోండి (Register)',
    signOut: 'లాగ్ అవుట్ (Sign Out)',

    whatSahaayDoes: 'సహాయ్ ఏమి చేస్తుంది (What Sahaay Does)',
    whatSahaaySubtitle: 'సహానుభూతి, పారదర్శకత మరియు మానవ పర్యవేక్షణతో కూడిన AI గుర్తింపు (AI-assisted detection and monitoring).',
    card1Title: 'బహుభాషా మద్దతు (Multilingual Support)',
    card1Desc: 'వచనం లేదా స్వరం ద్వారా మీ భాషలో మాట్లాడండి (Communicate using text or voice).',
    card2Title: 'ప్రారంభ ప్రమాద సంకేతాలు (Early Distress Signals)',
    card2Desc: 'బాధాకరమైన భావోద్వేగ సంకేతాల AI గుర్తింపు (AI-assisted identification of distress signals).',
    card3Title: 'డైనమిక్ పర్యవేక్షణ (Dynamic Monitoring)',
    card3Desc: 'ప్రమాద స్థాయి మార్పులను నిరంతరం ట్రాక్ చేయండి (Track changes in vulnerability indicators).',
    card4Title: 'మానవ-కేంద్రీకృత మద్దతు (Human-Centered Support)',
    card4Desc: 'AI అంతర్దృష్టులను అందిస్తుంది, అధికారులు నిర్ణయం తీసుకుంటారు (AI provides advisory insights).',

    howSahaayWorks: 'సహాయ్ ఎలా పనిచేస్తుంది (How Sahaay Works)',
    howSahaaySubtitle: 'ప్రతి కేసుకు సరైన శ్రద్ధ లభించేలా రూపొందించిన 6 దశల ప్రక్రియ (A structured six-step workflow).',
    step1Title: '01. వినడం (LISTEN)',
    step1Desc: 'మీరు చెప్పేది మేము శ్రద్ధగా వింటాము (We listen to what you share).',
    step2Title: '02. అర్థం చేసుకోవడం (UNDERSTAND)',
    step2Desc: 'AI సందర్భాన్ని మరియు భాషను అర్థం చేసుకుంటుంది (AI understands context and language).',
    step3Title: '03. మూల్యాంకనం (ASSESS)',
    step3Desc: 'ప్రమాద సంకేతాల AI మూల్యాంకనం (AI-assisted assessment of signals).',
    step4Title: '04. వివరణ (EXPLAIN)',
    step4Desc: 'వివరాలు స్పష్టంగా వివరించబడతాయి (Insights are explained clearly).',
    step5Title: '05. మానవ సమీక్ష (HUMAN REVIEW)',
    step5Desc: 'అధీకృత అధికారులు కేసును సమీక్షిస్తారు (Authorized personnel review the case).',
    step6Title: '06. మద్దతు (SUPPORT)',
    step6Desc: 'సరైన మద్దతు మరియు మార్గదర్శకత్వం అందుతుంది (Appropriate support follows).',

    privacyTitle: 'గోప్యత మరియు భద్రత ప్రథమం (Privacy & Security First)',
    privacyStatement: 'మీ డేటా సురక్షితం మరియు గోప్యమైనది (Your data is safe and confidential).',
    dangerTitle: 'మీరు తక్షణ ప్రమాదంలో ఉన్నారా? (In Immediate Danger?)',
    dangerDesc: 'వెంటనే 112 లేదా 1091 కి కాల్ చేయండి (Call 112 or 1091 immediately).',
    emergencyDir: 'అత్యవసర డైరెక్టరీ (Emergency Directory)',

    intakeBadge: 'ఎన్‌క్రిప్ట్ చేయబడిన ఛానల్ (Encrypted Channel · NHAA 14566)',
    intakeTitle: 'మీ ఫిర్యాదును మాట్లాడండి లేదా నమోదు చేయండి (Submit or Speak Your Grievance)',
    intakeDesc: 'మీ సమస్యను మీ స్వంత మాటల్లో తెలియజేయండి (Express your situation freely in your own words).',
    clickToSpeak: 'మాట్లాడటానికి క్లిక్ చేయండి (Click to Speak / Speak Now)',
    listening: 'వింటున్నాము... మాట్లాడండి (Listening... Speak in any language / Hinglish)',
    micEncrypted: 'మైక్రోఫోన్ ఆడియో సురక్షితంగా ఎన్‌క్రిప్ట్ చేయబడింది (Microphone audio encrypted in transit)',
    typeStatement: 'వివరణ రాయండి లేదా సవరించండి (Type or Edit Statement)',
    pasteSample: 'తెలుగు నమూనా పాఠాన్ని అతికించండి (Paste Sample Text) →',
    placeholder: 'మీ సమస్యను ఇక్కడ టైప్ చేయండి...',
    consentText: 'నేను గోప్యతా నిబంధనలకు అంగీకరిస్తున్నాను (I consent to privacy protocols).',
    submitBtn: 'సమీక్ష కోసం సమర్పించండి (Submit for Officer Triage)',
    docketSuccess: 'ఫిర్యాదు విజయవంతంగా నమోదైంది (Grievance Registered Successfully)',
    docketPrompt: 'మీ డాకెట్ నంబర్ (Your Docket Number)',
    docketSub: 'ఈ నంబర్‌ను భద్రపరుచుకోండి (Save this docket number).',
    trackGrievanceBtn: 'ఫిర్యాదు స్థితిని చూడండి (Track Grievance Status) →',
    returnHome: 'హోమ్‌కు తిరిగి వెళ్లండి (Return to Home)',

    trackTitle: 'ఫిర్యాదు స్థితిని ట్రాక్ చేయండి (Track Grievance Status)',
    trackDesc: 'పురోగతిని చూడటానికి డాకెట్ నంబర్‌ను నమోదు చేయండి (Enter docket number).',
    trackPlaceholder: 'ఉదా. NHAA/2026/05/2841',
    trackButton: 'స్థితిని ట్రాక్ చేయండి (Track Status)',
    quickDockets: 'నమూనా డాకెట్లు (Demo Dockets):',

    welcome: 'స్వాగతం, పౌరులారా 👋 (Welcome, Citizen)',
    dashboardSub: 'ఫిర్యాదులను సురక్షితంగా నమోదు చేయండి మరియు సహాయం పొందండి (Submit concern safely).',
    dashCard1Title: 'ఫిర్యాదు దాఖలు చేయండి (Register a Grievance)',
    dashCard1Desc: 'మీ స్వరం లేదా వ్రాతపూర్వక రూపంలో ఫిర్యాదు చేయండి (Use voice or text).',
    dashCard2Title: 'ఫిర్యాదు స్థితిని ట్రాక్ చేయండి (Track Status)',
    dashCard2Desc: 'పురోగతి మరియు పరిష్కార సమయాన్ని గమనించండి (Monitor milestones).',
    dashCard3Title: 'నా చట్టపరమైన హక్కులు (My Legal Rights)',
    dashCard3Desc: 'ఉచిత న్యాయ సహాయం సమాచారం (Free legal aid services).',
    dashCard4Title: 'అత్యవసర హెల్ప్‌లైన్లు (Emergency Helplines)',
    dashCard4Desc: '112, 1091 మరియు 14566 నంబర్లకు తక్షణ కాల్ (Direct hotline access).'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('sahaay_selected_lang') || 'en'
  })

  const setLanguage = (langCode) => {
    setLanguageState(langCode)
    localStorage.setItem('sahaay_selected_lang', langCode)

    try {
      const googleLang = langCode === 'hinglish' ? 'hi' : langCode
      document.cookie = `googtrans=/en/${googleLang}; path=/;`
      document.cookie = `googtrans=/en/${googleLang}; path=/; domain=${window.location.hostname};`
      const select = document.querySelector('.goog-te-combo')
      if (select) {
        select.value = googleLang
        select.dispatchEvent(new Event('change', { bubbles: true }))
      }
    } catch (e) {
      console.warn('Google Translate sync error:', e)
    }
  }

  const t = (key) => {
    const langDict = translations[language] || translations.en
    return langDict[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
